version: "3.9"

services:
  app:
    image: ${ECR_URI}:${IMAGE_TAG}
    container_name: shreyan-ignite
    restart: unless-stopped
    ports:
      - "80:3000"     # <-- change 3000 to whatever port your app listens on inside the container
    env_file:
      - .env
